#!/bin/bash
bash cleanup.sh he
bash cleanup.sh sv
bash cleanup.sh ca
bash cleanup.sh hu
bash cleanup.sh bg
bash cleanup.sh ar
bash cleanup.sh cs
bash cleanup.sh fi
bash cleanup.sh no
bash cleanup.sh fa
bash cleanup.sh sr
bash cleanup.sh vi
bash cleanup.sh tr
bash cleanup.sh id
bash cleanup.sh ro
bash cleanup.sh th
bash cleanup.sh da
bash cleanup.sh hr
bash cleanup.sh lt
bash cleanup.sh sk
bash cleanup.sh sl
bash cleanup.sh et
bash cleanup.sh ms
bash cleanup.sh el
bash cleanup.sh ko
bash cleanup.sh ja
bash cleanup.sh nl
bash cleanup.sh en
bash cleanup.sh de
bash cleanup.sh lv
bash cleanup.sh hi
bash cleanup.sh es
bash cleanup.sh it
bash cleanup.sh fr
bash cleanup.sh ru
bash cleanup.sh pl
bash cleanup.sh uk
bash cleanup.sh pt
bash cleanup.sh zh
