#!/bin/bash
bash magic.sh ja gru 3
bash magic.sh nl gru 3
bash magic.sh en gru &
bash magic.sh de gru &
bash magic.sh lv gru &
bash magic.sh hi gru 3
bash magic.sh es gru 3
bash magic.sh it gru 3
bash magic.sh fr gru 3
bash magic.sh ru gru 3
bash magic.sh pl gru 3
bash magic.sh uk gru 3
bash magic.sh pt gru 3
bash magic.sh zh gru 3
bash magic.sh he gru 3
bash magic.sh sv gru 3
bash magic.sh ca gru 3
bash magic.sh hu gru 3
bash magic.sh bg gru 3
bash magic.sh ar gru 3
bash magic.sh cs gru 3
bash magic.sh fi gru 3
bash magic.sh no gru 3
bash magic.sh fa gru 3
bash magic.sh sr gru 3
bash magic.sh vi gru 3
bash magic.sh tr gru 3
bash magic.sh id gru 3
bash magic.sh ro gru 3
bash magic.sh th gru 3
bash magic.sh da gru 3
bash magic.sh hr gru 3
bash magic.sh lt gru 3
bash magic.sh sk gru 3
bash magic.sh sl gru 3
bash magic.sh et gru 3
bash magic.sh ms gru 3
bash magic.sh el gru 3
bash magic.sh ko gru 3
