#!/bin/bash
bash magic.sh ja 0B5lWReQPSvmGYzlWMC1KcV9kVzQ 3
bash magic.sh nl 0B5lWReQPSvmGT19qd0UxaU9ZVjQ 3
bash magic.sh en 0B5lWReQPSvmGOTNxdHo3b0lMc3c &
bash magic.sh de 0B5lWReQPSvmGNm0zdUgyakZBeVU &
bash magic.sh lv 0B5lWReQPSvmGdEZMc3hqMWFnZ1k &
bash magic.sh hi 0B5lWReQPSvmGLUtnWk1mN2VOU0k &
bash magic.sh es 0B5lWReQPSvmGOXdCZEZPSnZoYXc &
bash magic.sh it 0B5lWReQPSvmGSHdkcDhlaGhMVnc &
bash magic.sh fr 0B5lWReQPSvmGdkIxeVJESWcyVU0 &
bash magic.sh ru 0B5lWReQPSvmGcGJIa196bVQ0Sjg &
bash magic.sh pl 0B5lWReQPSvmGcHptUXRIQ1JBSjg 3
bash magic.sh uk 0B5lWReQPSvmGbnVjd1JsOGhfOG8 3
bash magic.sh pt 0B5lWReQPSvmGR1RkVzBKeUJVYnM 3
bash magic.sh zh 0B5lWReQPSvmGTE5kMC1EcEpEV2M 3
bash magic.sh he 0B5lWReQPSvmGWU9NdDhtbUpBbjg 3
bash magic.sh sv 0B5lWReQPSvmGNVZab2R6U3hqcU0 3
bash magic.sh ca 0B5lWReQPSvmGLWdHUXQ0c0NuVXc 3
bash magic.sh hu 0B5lWReQPSvmGanZwWlp3UlFERVE 3
bash magic.sh bg 0B5lWReQPSvmGWTZHd3czWTRFMlU 3
bash magic.sh ar 0B5lWReQPSvmGcEw0Qk5PMUVwR0k 3
bash magic.sh cs 0B5lWReQPSvmGNUZCdnp5em14SWs 3
bash magic.sh fi 0B5lWReQPSvmGNXQta05VelBSVlU 3
bash magic.sh no 0B5lWReQPSvmGWUtlQU1aS2Q1Smc 3
bash magic.sh fa 0B5lWReQPSvmGVXJrODBDSHhDSVE 3
bash magic.sh sr 0B5lWReQPSvmGbE0zZ0x4OGk0TG8 3
bash magic.sh vi 0B5lWReQPSvmGbDhfd2ZTUThqUWs 3
bash magic.sh tr 0B5lWReQPSvmGMk5qM3dJOFg4YXM 3
bash magic.sh id 0B5lWReQPSvmGd0pqQjRqRmRDaE0 3
bash magic.sh ro 0B5lWReQPSvmGNXpNblFpazVZQlE 3
bash magic.sh th 0B5lWReQPSvmGdDQ5LU1xeW9hU1U 3
bash magic.sh da 0B5lWReQPSvmGSVRRQmlOMTFKRzQ 3
bash magic.sh hr 0B5lWReQPSvmGVklRSTREb0FmcVE 3
bash magic.sh lt 0B5lWReQPSvmGWW9CMkR6QjhIanc 3
bash magic.sh sk 0B5lWReQPSvmGWnVuUHZPdXBVWTQ 3
bash magic.sh sl 0B5lWReQPSvmGempGVWpuNnpDR0U 3
bash magic.sh et 0B5lWReQPSvmGeFBYbUtYdEJWY3M 3
bash magic.sh ms 0B5lWReQPSvmGOE5uSVdPTDg3VFU 3
bash magic.sh el 0B5lWReQPSvmGazIyd2xyZl9KNkE 3
bash magic.sh ko 0B5lWReQPSvmGQk9QUW5iem9ZZU0 3
